### ISSUE TITLE
Website isn't responsive for smaller screens.

### ISSUE THREAD

**Issue by chtushar** [connieliu0/p5.js-showcase#13]
The website is getting a horizontal scroll on mobile. Please refer the screenshot below.

I have a solution for this issue, can you assign me this? Thanks.

![WhatsApp Image 2020-09-06 at 10 55 58 AM](https://user-images.githubusercontent.com/33191895/92318916-73326380-f030-11ea-96e9-cee92f7719d5.jpeg)

**Comment by connieliu0** [comment]
just assigned! thanks for the help. Would it be possible to push before Tuesday or Wednesday? (I'm publicizing the showcase then), if not I can take a look at it and try to fix it

**Comment by chtushar** [comment]
Yes, I'll push it before Tuesday. Thanks!

**Comment by connieliu0** [comment]
Awesome! Thanks for the help :)

**Comment by chtushar** [comment]
Hey @connieliu0 , Do you want language panel to go left and below navigation links on small devices?

**Comment by chtushar** [comment]
@connieliu0 Hey, I am almost done with the solution. Just one thing is left!

Can you tell me which component is this? I'm not able to find it.
Thanks.

![chrome-capture](https://user-images.githubusercontent.com/33191895/92324821-c9b89580-f062-11ea-8eda-16b6d419f455.jpg)

**Comment by connieliu0** [comment]
@chtushar it would be great if the language bar could be underneath the nav bar! on the full size it is to the left though. Also, the component that holds the stars has the id "P5Wrapper" and the code that links the sketch to the main page is       <P5Wrapper sketch={sketch}/>! I don't know why there is a giant margin to the left of the sketch though, it doesn't show up there on my screen.

**Comment by chtushar** [comment]
@connieliu0 Okay got it!

**Comment by chtushar** [comment]
* Header and hero section looks good now.
![output-onlinepngtools](https://user-images.githubusercontent.com/33191895/92382515-59754700-f12a-11ea-9590-955498587816.png)
* Description
![output-onlinepngtools (1)](https://user-images.githubusercontent.com/33191895/92382638-8b86a900-f12a-11ea-87c5-6b462f9031a5.png)
* Chart
![output-onlinepngtools (2)](https://user-images.githubusercontent.com/33191895/92382715-ae18c200-f12a-11ea-9abe-e734317ecb18.png)

* This part is little messed up soI've added `overflow-x: hidden` in CSS so it removes horizontal scrollbar completely.
![chrome-capture (2)](https://user-images.githubusercontent.com/33191895/92383293-b0c7e700-f12b-11ea-97dc-7c8dfd9dd40c.jpg)

One little suggestion, mobile phones anyway don't have space bar so we can hide "P5Wrapper" for mobile.

**Comment by chtushar** [comment]
Should I make a pull request?

**Comment by chtushar** [comment]
https://p5-js-showcase.vercel.app/ this one is with changes that I've made. :)

**Comment by connieliu0** [comment]
@chtushar a pull request would be great! I think I'll keep the viz up anyways (space bar just changes the colors/text), that way they know they can access the website on desktop for a fuller view!
