### ISSUE TITLE
Unexpected behaviour of scrollbars

### ISSUE THREAD

**Issue by covalentbond** [connieliu0/p5.js-showcase#16]
**Steps to reproduce:**

Visit: the [webpage](https://showcase.p5js.org/#/)
Scrollbars are toggling repeatedly from normal position to overflowed because of the visualizations

![image](https://user-images.githubusercontent.com/53327173/105200399-cdf2d480-5b65-11eb-9b71-714e4592d897.png)

I would like to fix this :)

**Comment by connieliu0** [comment]
fixed!
