### ISSUE TITLE
Spanish translation plurals and generics are wrong

### ISSUE THREAD

**Issue by luis-santos** [connieliu0/p5.js-showcase#18]
In spanish, the generic word for welcome is "bienvenido", "bienvenide" is not even a word in spanish, it's like if you said "welcomu" in english. Same happens with "elles" in this page, the correct word is "ellos".

I know you guys have pressure from some groups regarding gender stuff, but I think this should not mean a wrong use of our language.

Bienvenide (wrong) -> Bienvenido (right)
https://github.com/connieliu0/p5.js-showcase/blob/7d82e94847b6a8d77a8f2c79827c6c8d26b6a9ac/src/locales/es/translation.json#L32

elles (wrong) -> ellos (right)
https://github.com/connieliu0/p5.js-showcase/blob/7d82e94847b6a8d77a8f2c79827c6c8d26b6a9ac/src/locales/es/translation.json#L38

Kind regards,

Luis.

**Comment by montoyamoraga** [comment]
hi @luis-santos, thanks for the recommendation,
i did the Spanish translation, they are not wrong words,
they are just newer and not as widespread,
but they are getting more and more popular,
i hope you understand, best!

**Comment by luis-santos** [comment]
Hi Aarón,

Don't get me wrong, this is not a recommendation, this is just a heads up on bad grammar use in this website. Grammar is not an opinion, the words "bienvenide" and "elles" are not spanish words, they are not well constructed, and nobody uses them besides small groups, in a forced way, when they want to do political gender propaganda. If I take the time to write this is because misspelling in a website is unprofessional and it's bad for the project itself, I'm trying to help you guys out here. A tech website displaying this kind of made up language looks like a joke or just propaganda.

I hope *you* understand!

**Comment by montoyamoraga** [comment]
hi,
language are constructs and fluid,
and you are not following our community statement,
https://p5js.org/community/
so i won't reply anymore
