### ISSUE TITLE
Adding Hindi language translations 

### ISSUE THREAD

**Issue by Rahulm2310** [connieliu0/p5.js-showcase#19]
Currently we have translations for `English`, `Spanish`, `Chinese` and one more language (don't know). `Hindi` language is mother tongue to Indians and spoken commonly in some asian countries. 

There should be translations for hindi on the project.

**Comment by Rahulm2310** [comment]
@connieliu0 @montoyamoraga Does this seems valid? If yes, I would like to work on this. 🙂

**Comment by montoyamoraga** [comment]
hi @Rahulm2310 thanks!

this website was developed by @connieliu0, so it should be her call :)

i think it would be great to have more translations, but i do prefer that any translation should be done by two people at least, for editing and corrections.

also, for maintenance and consistence i prefer that this showcase and the main p5.js website have the same languages, so i vote no to you working on this on your own, sorry!

we have added more languages to the p5.js website through long-time efforts,
usually through Google Summer of Code and Processing Fellowships :)
i highly encourage to apply if you are interested! it would be a great fit!
https://medium.com/processing-foundation/open-call-for-2021-fellowships-44c777cc335

we have an in-progress hindi translation of the whole website, i don't know its current state, maybe you would be interested in that? :)
https://github.com/processing/p5.js-website/tree/hindi
https://medium.com/processing-foundation/interview-with-2019-fellows-manaswini-das-nancy-chauhan-and-shaharyar-shamshi-172127c2e277

**Comment by connieliu0** [comment]
Hi @Rahulm2310  +1 to @montoyamoraga's comment - it might be better to contribute to the main p5.js website's translation progress instead! we can revisit translating the showcase afterwards!

**Comment by Rahulm2310** [comment]
Sure. thanks @connieliu0 @montoyamoraga. This can be put on hold for now 👍

**Comment by Rahulm2310** [comment]
Hi @montoyamoraga. Can you please have a look at my fellowship [proposal](https://docs.google.com/document/d/1EMzcxjASOKnj9etIWxlklvSsxA6mfr76-NQVILC-Ywo/edit?usp=sharing) for hindi translation   and give your feedback. Thanks 🙂

**Comment by montoyamoraga** [comment]
hi @Rahulm2310 it looks great to me, thanks for making such a thoughtful application, fingers crossed, it is a very competitive fellowship, please don't be disencouraged if you don't get it this year :)

**Comment by Rahulm2310** [comment]
Hi @montoyamoraga , I was looking into automating the process of translation with a script. Here's a link to a similar [script](https://github.com/tewen/gtd-scripts/blob/master/translate-json). The problem with this is it uses google's translate API which is a paid service. So will it be ideal for us to use a paid service ? Please share your views.

**Comment by montoyamoraga** [comment]
hi @Rahulm2310 my translation to Spanish, and as far as i know the other ones, were done without automation or translation services, and there are so many complexities in language, that i rather have the translations be done by people. Last time I checked Google Chrome too, it is possible to ask for it to translate whole websites for you, so it wouldn't add to have an automated translation in the website, right?

**Comment by montoyamoraga** [comment]
also, this is a larger discussion that i think belongs to the main p5.s repository, most probaby to an already existing issue or PR, so i rather not continue brainstorming on this thread, so we can close this issue ~

**Comment by connieliu0** [comment]
This is a really insightful discussion but yes I think the main p5js repo would be ideal!
