### ISSUE TITLE
[Map Interaction] Disable scroll zoom

### ISSUE THREAD

**Issue by joeyklee** [connieliu0/p5.js-showcase#3]
Hi!
You might consider disabling the scroll zoom so that when people are scrolling on your page they don't affect the zoom. If yo decide to disable scroll zoom, make sure to include the zoom button controls so people can still zoom around. 

* https://leafletjs.com/reference-1.6.0.html#map-scrollwheelzoom

**Comment by connieliu0** [comment]
Just changed!
