### ISSUE TITLE
[Acknowlegements] Add acknowledgements section

### ISSUE THREAD

**Issue by joeyklee** [connieliu0/p5.js-showcase#4]
Hi!

It would be great to add an acknowledgements section to the About page. Here you can add in acknowledgements to:
* Funding & supporting organizations:
  - GSOC, Processing Foundation, 
* Under the supervision & mentorship of:
  - Yining Shi
  - Joey Lee
  - Lauren McCarthy
  - p5 maintainers and contributors
* ... (any other relevant acknowledgement sections and people)

**Comment by connieliu0** [comment]
just added!
